### ISSUE TITLE
Icons Missing in Footer and other areas

### ISSUE THREAD

**Issue by haitzlm** [uclibs/aaec#161]
Edit: not just footer
Font Awesome icons not showing in footer, and also in "edit" view of submissions:
![missing-font](https://user-images.githubusercontent.com/493654/202268271-965d1128-1fae-4cec-8324-3705b41026cb.jpg)

**Comment by lisa3711** [comment]
The path to font awesome in our code is:
 <script src="https://kit.fontawesome.com/a076d05399.js"></script>
If one tries to access that script, you get an error:
`Not allowed when Origin missing`
So I think font awesome is not loading correctly, due to cross browser. There is a gem for font awesome:
- https://fontawesome.com/docs/web/use-with/ruby-on-rails
