### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by hortongn** [uclibs/aaec#178]
### Descriptive summary

TBD.  After needed security, UI, and other changes, take the application through the required deploy process (testing, security scan, change management, etc.)

**Comment by Janell-Huyck** [comment]
**_Preparing for deployment process tasks:_**

- [ ] accessibility
- [ ] security
- [ ] change management
- [ ] write a click-through testing script

**_Pre-Deploy Tasks:_**

- [ ] add a new production and qa environment variable MAIL_SMTP_ADDRESS to hold the correct certificate address.
- [ ] Update config vault files with new env variable
- [ ] Inform all UC Libapps developers of change to .env file.
- [ ] check that the certificate on **libapps** is up to date
- [ ] locate the IP address for **libapps**
- [ ] modify on **libapps** _etc/postfix/main.cf_ the line `inet_interfaces = localhost` so that it instead says `inet_interfaces = 127.0.0.1, ::1, our.ip.address.here`.
- [ ] restart the postfix service
- [ ] verify the following env variables: EXPIRATION_DATE, PAST_DATE
- [ ] verify if we need to delete any testing submissions made after deployment

**_Post-Deploy Tasks:_**
- [ ] Set production PAST_DATE so that we can do click-through testing
- [ ] Click-through tests, including making a submission that should send an email
- [ ] Change the production PAST_DATE back to the correct value
- [ ] Notify Melissa that updates have occurred and to expect a couple testing emails just today
- [ ] Notify any other stakeholders for aaec

**Comment by Janell-Huyck** [comment]
Deploying to production 4/16/2024
