### ISSUE TITLE
Security - Large Issue with Migrations - Create a user model and allow user to sign in with a password

### ISSUE THREAD

**Issue by Janell-Huyck** [uclibs/aaec#320]
Currently, when we check to see if a user is logged in as a submitter, we check to see if `session[:submitter_id]` is present or not.  If there is an id, we assume the user is correctly logged in as a submitter.  There is no password check.

A better practice would be to have the user sign in with a password, and to connect a single submitter id to that user account.

A user should have:

- a user id (primary key)
- a submitter_id (foreign_key)
- an access level (submitter or admin)
- a hashed password
- a status of active (default) or inactive
- an email - UC or otherwise?? Verify with Melissa and Glen

Once the user logs in, it should look up what their submitter id is, and set the session[:submitter_id] to that id.

After this, 

We will need to create a way for the user to log in.  This should be done in a manner that is friendly to SSO and Devise so that we can implement it in the future.

We will need to add a way for users to filter their submissions for items that have been submitted in the current submission cycle - otherwise, if a user is submitting items over several years their list of publications might become unwieldy.

We will need to add pagination for the user indexes

We will need to add in a way for a user to change or reset their password - possibly through SSO or Devise?

We will need to add expiration to sessions, having a way for them to time out and log out a user after a period of inactivity.

We will need to remove or modify the 3-item per category limit - perhaps making it per session if Melissa wants it kept, otherwise perhaps removing it?

**Comment by haitzlm** [comment]
Devise can generate a lot of what you are talking about with some simple commands. Views, Models and Controllers...I was able to have my staff directory add an admin user, which can recover a lost password with email, shows certain views only if logged in, etc...

Regarding this:"We will need to add a way for users to filter their submissions for items that have been submitted in the current submission cycle - otherwise, if a user is submitting items over several years their list of publications might become unwieldy."

AAEC runs only for the current year. That is, it only accepts items within the last year (I think it is academic year). So, in most cases, you will have a submitter, and just the author of the work. Submitters should be the only people able to login. I don't even know if Melissa will care about the previous years frankly. 

Hope that makes sense!

**Comment by Janell-Huyck** [comment]
At this point, we do not want to do this significant re-work for AAEC.  Right now we are looking at changing the app to a static page for security purposes.
