### ISSUE TITLE
Don't default to the first college in the select list

### ISSUE THREAD

**Issue by hortongn** [uclibs/aaec#33]
The college select list should default to something like "Select your college..." instead of defaulting to "Allied Health Sciences"

**Comment by bsp3ars** [comment]
@hortongn After doing some research, I have come to 2 possible solutions.

1. if we are to include a blank and select it by default, then if we edit a user we lose what the original value is
2. We don't change it

The reason behind this is because `options_from_collection_for_select` doesn't have the include_blank option, but select_tag does. And since the select initializes and then loads the data, it will automatically set it to the default which is blank.
